name: training
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter_stripe: ^10.1.1
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2+1
  pocketbase: ^0.17.0

  #--State managment
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  dartz: ^0.10.1
  get_it: ^7.6.0
  provider: ^6.0.5
  path: ^1.8.3
  path_provider: ^2.1.1

  #--Local Data
  shared_preferences: ^2.2.0
  internet_connection_checker_plus: ^2.0.0
  intl: ^0.18.1

# dependency_overrides:
#   stripe_android: "9.5.0+1"
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true